#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TARGET_REPO="TiagoJacinto/runtime-visualizer"
TOTAL_STAGES=4

banner "PR Lens source-linked setup"

stage "Choose the Gemini model"
say "Choose the model the GitHub Action will use to extract the graph."
open_url "https://ai.google.dev/gemini-api/docs/models"
step "Use gemini-2.5-flash for the recommended balance of quality and free-tier usage."
step "Use gemini-2.5-flash-lite if Flash reaches its free quota."
ask PR_LENS_MODEL "Model [gemini-2.5-flash]:"
PR_LENS_MODEL="${PR_LENS_MODEL:-gemini-2.5-flash}"
case "$PR_LENS_MODEL" in
  gemini-2.5-flash|gemini-2.5-flash-lite) ;;
  *) warn "Use gemini-2.5-flash or gemini-2.5-flash-lite."; exit 1 ;;
esac
GH_REPO="$TARGET_REPO" set_var PR_LENS_MODEL "$PR_LENS_MODEL"

stage "Create the Gemini API key"
say "Create a Gemini API key and save it directly as a GitHub Actions secret."
open_url "https://aistudio.google.com/app/apikey"
step "Select Create API key, choose the account/project you want, and copy the key."
step "Do not paste the key into a workflow file or commit it to Git."
ask_secret GEMINI_API_KEY "Paste the Gemini API key:"
if [[ -z "$GEMINI_API_KEY" ]]; then
  warn "No API key was provided; re-run the wizard and paste it in this stage."
  exit 1
fi
GH_REPO="$TARGET_REPO" set_secret GEMINI_API_KEY "$GEMINI_API_KEY"

stage "Add the GitHub workflow"
say "Create this file in the runtime-visualizer repository."
open_url "https://github.com/${TARGET_REPO}/new/main?filename=.github%2Fworkflows%2Fpr-lens.yml"
step "Set the file path to .github/workflows/pr-lens.yml, then paste this exact content:"
cat <<'YAML'
name: PR Lens

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: pr-lens-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  lens:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: TiagoJacinto/pr-lens/packages/action@feat/clickable-source-nodes
        with:
          api-key: ${{ secrets.GEMINI_API_KEY }}
          model: ${{ vars.PR_LENS_MODEL }}
          cli-source: workspace
          canvas-url: ${{ vars.PR_LENS_CANVAS_URL }}
          canvas-publish-token: ${{ secrets.PR_LENS_CANVAS_PUBLISH_TOKEN }}
YAML
step "Commit the new workflow to the default branch."
if ! confirm "Have you committed .github/workflows/pr-lens.yml?"; then
  warn "The workflow is not active yet. Re-run this stage after committing it."
  exit 1
fi

stage "Verify the setup"
say "Check that GitHub can see the workflow and all three integration values."
if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  warn "GitHub CLI is not authenticated; verify these names manually in repository Settings."
  SKIPPED+=("Verify workflow, GEMINI_API_KEY, PR_LENS_CANVAS_URL, and PR_LENS_CANVAS_PUBLISH_TOKEN in ${TARGET_REPO}")
else
  if gh workflow view pr-lens.yml --repo "$TARGET_REPO" >/dev/null 2>&1; then
    printf '  %s✓ found%s workflow pr-lens.yml\n' "$GREEN" "$RESET"
  else
    warn "GitHub cannot find pr-lens.yml yet; check that it was committed on the default branch."
    SKIPPED+=("Make pr-lens.yml visible on the default branch")
  fi
  for secret in GEMINI_API_KEY PR_LENS_CANVAS_PUBLISH_TOKEN; do
    if gh secret list --repo "$TARGET_REPO" | awk '{print $1}' | grep -Fxq "$secret"; then
      printf '  %s✓ found%s GitHub secret %s\n' "$GREEN" "$RESET" "$secret"
    else
      warn "Missing GitHub secret $secret."
      SKIPPED+=("Set GitHub secret $secret")
    fi
  done
  if gh variable list --repo "$TARGET_REPO" | awk '{print $1}' | grep -Fxq PR_LENS_MODEL && \
     gh variable list --repo "$TARGET_REPO" | awk '{print $1}' | grep -Fxq PR_LENS_CANVAS_URL; then
    printf '  %s✓ found%s GitHub variables PR_LENS_MODEL and PR_LENS_CANVAS_URL\n' "$GREEN" "$RESET"
  else
    warn "Missing PR_LENS_MODEL or PR_LENS_CANVAS_URL GitHub variable."
    SKIPPED+=("Set GitHub variables PR_LENS_MODEL and PR_LENS_CANVAS_URL")
  fi
fi
open_url "https://github.com/${TARGET_REPO}/actions/workflows/pr-lens.yml"
say "The next same-repository pull request, or the next push to one, will run PR Lens."
# ──────────────────────────────────────────────────────────────────────────

finish
